/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Validator;
import Model.Phone;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class ManagementForm extends javax.swing.JFrame {
    public ArrayList<Phone> List = new ArrayList<>();
    /**
     * Creates new form ManagementForm
     */
    public ManagementForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitle = new javax.swing.JPanel();
        javax.swing.JLabel lblTitle = new javax.swing.JLabel();
        pnlLayoutAddInfo = new javax.swing.JPanel();
        pnlAddInfo = new javax.swing.JPanel();
        tblAddInfo = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblBrand = new javax.swing.JLabel();
        cbbBrand = new javax.swing.JComboBox<>();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblOrigin = new javax.swing.JLabel();
        cbbOrigin = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        pnlLayoutResult = new javax.swing.JPanel();
        pnlResult = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnReload = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbeResult = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        pnlTitle.setBackground(new java.awt.Color(102, 0, 255));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("SFU Helvetica", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("SMART PHONE STORE MANAGEMENT APP");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlLayoutAddInfo.setBackground(new java.awt.Color(255, 255, 255));

        pnlAddInfo.setBackground(new java.awt.Color(255, 102, 51));

        tblAddInfo.setBackground(new java.awt.Color(255, 255, 255));
        tblAddInfo.setFont(new java.awt.Font("SFU Helvetica", 0, 18)); // NOI18N
        tblAddInfo.setForeground(new java.awt.Color(255, 255, 255));
        tblAddInfo.setText("Add Information");
        tblAddInfo.setMaximumSize(new java.awt.Dimension(130, 30));
        tblAddInfo.setMinimumSize(new java.awt.Dimension(130, 30));
        tblAddInfo.setPreferredSize(new java.awt.Dimension(130, 30));

        javax.swing.GroupLayout pnlAddInfoLayout = new javax.swing.GroupLayout(pnlAddInfo);
        pnlAddInfo.setLayout(pnlAddInfoLayout);
        pnlAddInfoLayout.setHorizontalGroup(
            pnlAddInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddInfoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tblAddInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        pnlAddInfoLayout.setVerticalGroup(
            pnlAddInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddInfoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tblAddInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        lblID.setForeground(new java.awt.Color(0, 0, 0));
        lblID.setText("ID*");

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setPreferredSize(new java.awt.Dimension(70, 30));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setText("Name*");

        txtName.setBackground(new java.awt.Color(255, 255, 255));
        txtName.setPreferredSize(new java.awt.Dimension(64, 30));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblBrand.setForeground(new java.awt.Color(0, 0, 0));
        lblBrand.setText("Brand*");

        cbbBrand.setBackground(new java.awt.Color(255, 255, 255));
        cbbBrand.setForeground(new java.awt.Color(51, 51, 51));
        cbbBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apple", "Samsung", "Xiaomi", "Huawei" }));
        cbbBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbBrandActionPerformed(evt);
            }
        });

        lblPrice.setForeground(new java.awt.Color(0, 0, 0));
        lblPrice.setText("Price*");

        txtPrice.setBackground(new java.awt.Color(255, 255, 255));
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        lblOrigin.setForeground(new java.awt.Color(0, 0, 0));
        lblOrigin.setText("Origin*");

        cbbOrigin.setBackground(new java.awt.Color(255, 255, 255));
        cbbOrigin.setForeground(new java.awt.Color(51, 51, 51));
        cbbOrigin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Original", "International" }));
        cbbOrigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbOriginActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.setPreferredSize(new java.awt.Dimension(80, 22));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLayoutAddInfoLayout = new javax.swing.GroupLayout(pnlLayoutAddInfo);
        pnlLayoutAddInfo.setLayout(pnlLayoutAddInfoLayout);
        pnlLayoutAddInfoLayout.setHorizontalGroup(
            pnlLayoutAddInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlLayoutAddInfoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlLayoutAddInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLayoutAddInfoLayout.createSequentialGroup()
                        .addGroup(pnlLayoutAddInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLayoutAddInfoLayout.createSequentialGroup()
                        .addGroup(pnlLayoutAddInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbbBrand, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbOrigin, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40))
                    .addGroup(pnlLayoutAddInfoLayout.createSequentialGroup()
                        .addGroup(pnlLayoutAddInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlLayoutAddInfoLayout.setVerticalGroup(
            pnlLayoutAddInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayoutAddInfoLayout.createSequentialGroup()
                .addComponent(pnlAddInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pnlLayoutResult.setBackground(new java.awt.Color(255, 255, 255));

        pnlResult.setBackground(new java.awt.Color(0, 204, 0));

        txtSearch.setBackground(new java.awt.Color(255, 255, 255));

        btnSearch.setText("Search");
        btnSearch.setPreferredSize(new java.awt.Dimension(80, 22));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlResultLayout = new javax.swing.GroupLayout(pnlResult);
        pnlResult.setLayout(pnlResultLayout);
        pnlResultLayout.setHorizontalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlResultLayout.setVerticalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResultLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        btnEdit.setText("Edit");
        btnEdit.setPreferredSize(new java.awt.Dimension(80, 22));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnReload.setText("Reload");
        btnReload.setPreferredSize(new java.awt.Dimension(80, 22));
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.setPreferredSize(new java.awt.Dimension(80, 22));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.setPreferredSize(new java.awt.Dimension(80, 22));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        tbeResult.setBackground(new java.awt.Color(255, 255, 255));
        tbeResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Brand", "Price", "Origin"
            }
        ));
        tbeResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbeResultMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbeResult);

        javax.swing.GroupLayout pnlLayoutResultLayout = new javax.swing.GroupLayout(pnlLayoutResult);
        pnlLayoutResult.setLayout(pnlLayoutResultLayout);
        pnlLayoutResultLayout.setHorizontalGroup(
            pnlLayoutResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLayoutResultLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlLayoutResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlLayoutResultLayout.createSequentialGroup()
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnReload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        pnlLayoutResultLayout.setVerticalGroup(
            pnlLayoutResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayoutResultLayout.createSequentialGroup()
                .addComponent(pnlResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnlLayoutResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReload, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLayoutAddInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLayoutResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLayoutAddInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLayoutResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String search = txtSearch.getText();
        if (search. compareTo("") == 0){
            JOptionPane.showConfirmDialog(this, "Please information enter before search!");
        }
        else{
        String idRequest = search;
        DefaultTableModel tableModel = (DefaultTableModel) tbeResult.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(tableModel);
        tbeResult.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(idRequest));
        return;
        }
    }//GEN-LAST:event_btnSearchActionPerformed
                      
    
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:                 
        StringBuilder sb = new StringBuilder();
        Validator.checkId(txtID, sb);
        Validator.checkName(txtName, sb);
        Validator.checkPrice(txtPrice, sb);
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Invalid", JOptionPane.ERROR_MESSAGE);
        }
        else {
            DefaultTableModel tableModel = (DefaultTableModel)tbeResult.getModel();
            int i= tbeResult.getSelectedRow();
            if (i>=0){
                tableModel.setValueAt(txtID.getText(), i, 0);
                tableModel.setValueAt(txtName.getText(), i, 1);
                tableModel.setValueAt(cbbBrand.getSelectedItem(), i, 2);
                tableModel.setValueAt(txtPrice.getText(), i, 3);
                tableModel.setValueAt(cbbOrigin.getSelectedItem(), i, 4);
                JOptionPane.showMessageDialog(this, "Update Successfully");
            }
            else {
                JOptionPane.showMessageDialog(this, "Select a row");
            }                 
        }
                txtID.setText("");
        txtName.setText("");
	cbbBrand.setSelectedIndex(0);
        txtPrice.setText("");
        cbbOrigin.setSelectedIndex(0);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        // TODO add your handling code here:
        try {
            FileReader fileReader = new FileReader("SaveHere.txt");
            BufferedReader bufferedReader = new BufferedReader(fileReader);
            DefaultTableModel tableModel = (DefaultTableModel) tbeResult.getModel();
            Object[] lines = bufferedReader.lines().toArray();
            for (int i = 0; i < lines.length; i++) {
                String[] row = lines[i].toString().split(", ");
                tableModel.addRow(row);
            }
        } catch (FileNotFoundException e) {
                JOptionPane.showMessageDialog(this, "Error" + e);
            }
    }//GEN-LAST:event_btnReloadActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbModel = (DefaultTableModel) tbeResult.getModel();
        if (tbeResult.getSelectedRowCount()== 1) {
            tbModel.removeRow(tbeResult.getSelectedRow());
            JOptionPane.showMessageDialog(this, "The data has been deleted");                   
        }
        else {
            if (tbeResult.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "The data is empty");
            }
            else {
            JOptionPane.showMessageDialog(this, "Please select data to delete");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            FileOutputStream fout = new FileOutputStream("SaveHere.txt", true);
            
		for(Phone s: List) {
                    s.Save(fout);
		}
            JOptionPane.showMessageDialog(this, "Save Successfully");       
	}
	catch(Exception e) {
            System.out.println("Errol" + e);
	}
       
    }//GEN-LAST:event_btnSaveActionPerformed

    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:          
        StringBuilder sb = new StringBuilder();
        Validator.checkId(txtID, sb);
        Validator.checkName(txtName, sb);
        Validator.checkPrice(txtPrice, sb);
        if (sb.length() > 0) {
             JOptionPane.showMessageDialog(this, sb.toString(), "Invalid", JOptionPane.ERROR_MESSAGE);
        }            
        else{
            DefaultTableModel tbModel = (DefaultTableModel) tbeResult.getModel();
            Object table[] = {txtID.getText(),txtName.getText(),cbbBrand.getSelectedItem(),txtPrice.getText(),cbbOrigin.getSelectedItem()};
            tbModel.addRow(table);
            JOptionPane.showMessageDialog(this, "Added success");
            Phone phone = new Phone(Integer.parseInt(txtID.getText()), txtName.getText(),(Object) cbbBrand.getSelectedItem(), 
                    Integer.parseInt(txtPrice.getText()), (Object) cbbOrigin.getSelectedItem());
            List.add(phone);       
        }             

        txtID.setText("");
        txtName.setText("");
	cbbBrand.setSelectedIndex(0);
        txtPrice.setText("");
        cbbOrigin.setSelectedIndex(0);
        
                // TODO add your handling code here:
//        if (txtID.getText().equals("")) {
//            JOptionPane.showMessageDialog(this, "Error adding ID!");
//        }
//        else if (txtName.getText().equals("")) {
//            JOptionPane.showMessageDialog(this, "Error adding Name!");
//        }
//         else if (cbbBrand.getSelectedItem().equals("")) {
//            JOptionPane.showMessageDialog(this, "Error adding Brand!");
//        }
//         else if (txtPrice.getText().equals("")) {
//            JOptionPane.showMessageDialog(this, "Error adding Price!");
//        }
//         else if (cbbOrigin.getSelectedItem().equals("")) {
//            JOptionPane.showMessageDialog(this, "Error adding Origin!");
//        }
//         else {
//            DefaultTableModel tbModel = (DefaultTableModel) tbeResult.getModel();
//            Object table[] = {txtID.getText(),txtName.getText(),cbbBrand.getSelectedItem(),txtPrice.getText(),cbbOrigin.getSelectedItem()};
//            tbModel.addRow(table);
//            JOptionPane.showMessageDialog(this, "Added success");
//            Phone phone = new Phone(Integer.parseInt(txtID.getText()), txtName.getText(),(Object) cbbBrand.getSelectedItem(), txtPrice.getText(), (Object) cbbOrigin.getSelectedItem());
//            List.add(phone);
//        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void cbbBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbBrandActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void cbbOriginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbOriginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbOriginActionPerformed

    private void tbeResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbeResultMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) tbeResult.getModel();
        String tbID = tableModel.getValueAt(tbeResult.getSelectedRow(), 0).toString();
        String tbName = tableModel.getValueAt(tbeResult.getSelectedRow(), 1).toString();
        String tbBrand = tableModel.getValueAt(tbeResult.getSelectedRow(), 2).toString();
        String tbPrice = tableModel.getValueAt(tbeResult.getSelectedRow(), 3).toString();
        String tbOrigin = tableModel.getValueAt(tbeResult.getSelectedRow(), 4).toString();
        txtID.setText(tbID);
        txtName.setText(tbName);
        cbbBrand.setSelectedItem(tbBrand);
        txtPrice.setText(tbPrice);
        cbbOrigin.setSelectedItem(tbOrigin);      
    }//GEN-LAST:event_tbeResultMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagementForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbbBrand;
    private javax.swing.JComboBox<String> cbbOrigin;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrigin;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JPanel pnlAddInfo;
    private javax.swing.JPanel pnlLayoutAddInfo;
    private javax.swing.JPanel pnlLayoutResult;
    private javax.swing.JPanel pnlResult;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JTable tbeResult;
    private javax.swing.JLabel tblAddInfo;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

}
